version: '3'

services:
    users:
        container_name: 'users-service'
        #build: .
        image: 'raulplesa/pes-user-service'
        ports:
            - 13001:8000
        volumes:
            - './db.sqlite3:/app/db.sqlite3'
        restart: unless-stopped
